services:
  mu_fe_de:
    build:
      context: .
    container_name: mu_fe_de

    # Solo se monta el socket de X11 para soporte gráfico
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app

    environment:
      DISPLAY: ${DISPLAY}
      GRAPHQL_API: http://${mu_ag_HOSTNAME:-mu_ag}:${mu_ag_INTERNAL_PORT:-4000}/query
      ELECTRON_DISABLE_SANDBOX: "1"


    working_dir: /app

    user: "${UID:-1000}:${GID:-1000}"

